### ISSUE TITLE
Steam data extractor overwrites all data in non-empty folder

### ISSUE THREAD

**Issue by MrThomps0n** [Morta1/IdleonToolbox#100]
When setting a non-empty folder as the target db path the app overwrites the contents with the idleon db files.

ex: I set my downloads folder as the target path, and the app promply deleted all files that were there, save for 2 .exe files. (Don't feel bad, I did manage to recover the files)

Either different behaviour or a warning in the app saying that it will overwrite the entire folder would be a solution.

**Comment by Morta1** [comment]
Thank you for your suggestion, I've added a warning to the extractor.

You can download the new version [here](https://drive.google.com/file/d/1Q03J-kadz5iob45J1wnZWjnHhS0j0GgV/view?usp=sharing)
