### ISSUE TITLE
Suggestion: Link to Wiki information

### ISSUE THREAD

**Issue by maunzCache** [Morta1/IdleonToolbox#102]
Hi there,
 i really to like the toolbox, however i am missing some information that i need to get out of the "official" wiki at https://idleon.info/wiki . So to deduplicate source of in formation it would be cool to somehow include the information of the wiki partially in the tool
E.g. item informtion, questline information, ....

Best effort would be to query the wiki page by matching the required resource name and parse the returning HTML code. This is pretty awful but if could work. On the other hand a simple link generation would be fine as well. Should also allow players to integrate more information in the wiki as well :)

Yep that's basically it.

**Comment by Morta1** [comment]
Hey @maunzCache, what do you think is missing exactly? 
Can you give me an example of info you need and wasn't displayed?

**Comment by Morta1** [comment]
Closing this as I got no response
