### ISSUE TITLE
Display more trap information

### ISSUE THREAD

**Issue by Deraen** [Morta1/IdleonToolbox#103]
I think there is a chance the trap xp count (might be the value after trapTime) and critter count or efficiency are available on the raw data. Both trap xp and critter count are snapshotted at the time of the trap placement, so it would be useful to display those.

Also, in addition to time left, displaying the trap type (probably the value before trapTime) and time could be useful to keeping track if all chars are using correct traps.

**Comment by Morta1** [comment]
Thanks for the suggestions, added in #105
