### ISSUE TITLE
Cogstruction Empties bug

### ISSUE THREAD

**Issue by Nllv** [Morta1/IdleonToolbox#104]
This text is translated by a translation site and may contain errors.

There is a bug in the output of Cogstruction Empties.
The actual data on my game and the output data are different.
They are currently occurring in (2,2) (9,2) (5, 2), and I think they are more likely to occur when the flag is set.

**Comment by Morta1** [comment]
Hey, can you please share your data in a pastebin?

**Comment by Nllv** [comment]
Pastebin
https://pastebin.com/WQL29DCM

Toolbox
https://imgur.com/AcTIfm8
Mygame
https://imgur.com/K4xNJ8q

**Comment by Morta1** [comment]
Hey @Nllv, please copy all of your data from the home page of the idleontoolbox, by clicking the "COPY RAW JSON" button and pasting it into a paste bin

**Comment by Nllv** [comment]
The board has changed since the last time I pasted, but (5, 0) is now assumed not to be open.

RAW JSON
https://pastebin.com/butidhHu

**Comment by Morta1** [comment]
Sorry for asking again, but I will need to see an image and you updated data to see if something is wrong.

**Comment by Nllv** [comment]
Sorry for the delay in replying.
I was looking at the data and noticed that the Cogstruction Empties do not have the upper left as (0, 0)?
Cogstruction seems to have the bottom left as (0, 0).

**Comment by Morta1** [comment]
![image](https://user-images.githubusercontent.com/18611518/176991516-6958be46-a59c-486f-8f3c-7e4834fb7f3d.png)

I'm not sure I understand what you mean, the data seems to be correct.

**Comment by Nllv** [comment]
What I mean is the output of the data used in the empties_datas.csv.
This will be filled in with the "unopened mass coordinates".
IdleonToolbox output seems to be (0, 0) in the upper left corner.
Cogstruction Empties uses (0, 0) for the lower left.

**Comment by Morta1** [comment]
@Nllv Oh, didn't notice that.
I think I've fixed it in the latest commit, can you let me know if it's fixed for you?

**Comment by Nllv** [comment]
My board is now symmetrical and it will take 32 hours to check.
So you will ask someone else to check or I will post again after 32 hours.
Anyway, thank you for the fix.
