### ISSUE TITLE
Separate item planner into sections

### ISSUE THREAD

**Issue by FenixR** [Morta1/IdleonToolbox#107]
For example, you add the plans to make a chopping bag, logging bag and material bags, each one will be a section with the items needed to make each particular item so even if any of them share items with one another you can check how much you need for each one instead of just one grand total.

**Comment by FenixR** [comment]
Also even though equip items can be included it doesn't reduce the amount of materials to make some of the older item (Like trying to make a starfire pickaxe but you already have a lustre pickaxe, it still shows the item needed to make lustre pickaxe and below).

Issue can probably be solved by making an item count as unupgraded versions (Like having a lustre pickaxe counts as void/dementia/platinum etc)

**Comment by Morta1** [comment]
Added sections to the item planner, not sure when I'll implement the second part you suggested

**Comment by FenixR** [comment]
Works great 👍 

And yeah the second bit its more annoying so take your time with it.
