### ISSUE TITLE
Quests Page

### ISSUE THREAD

**Issue by crosbyb** [Morta1/IdleonToolbox#109]
I would love to see a count of the total quests completed (and total uncompleted) at the top of the Quests page when I have an individual character selected. This would be helpful for planning how many points I should put into Quest Chungus.

edit:It seems the in-game quest tracker literally tells me how many I've completed. 🤦 Well, stats/counters are good, it might still be cool to see how many I have completed and how many remain. :)

**Comment by Morta1** [comment]
As you said, it's kind of redundant to add this kind of feature, thanks for the suggestion 👍
