### ISSUE TITLE
Character's stats AFK time decreases

### ISSUE THREAD

**Issue by Dexxtre** [Morta1/IdleonToolbox#111]
In the Characters section and when you select "Stats" to view all the available stats, the AFK timer does not increase over time; rather, it decreases in the amount of time AFK'd, which I assume is not intended because that timer is presumably the amount of time a particular character has been AFK'ing. That amount of time should increase over time. Likely, it is an easy fix, but I thought to inform somebody.

**Comment by Morta1** [comment]
Thanks for the report, fixed on last commit

https://github.com/Morta1/IdleonToolbox/commit/f8fe8bb56b554e88cc2d105ff743b7801deb1695
