### ISSUE TITLE
Skill supplemental information

### ISSUE THREAD

**Issue by Zekaonar** [Morta1/IdleonToolbox#112]
Thanks for the super useful site!

When looking at the Account > World > Skills, it would be useful to see supplemental information about the skill that you already have elsewhere.  

World 1> Anvil display each character's Smithing skill lvl and points from mats and coins
World 3> Worship display each character's Worship lvl and equipped Skull
World 4> Trapping display each character's Trapping lvl and equipped Trap

Also is it possible to know if a character is in talent spec 1 or 2?  A common error I make is I switch specs to use a skill then forget to switch them back.  For me spec 1 is always fighting and spec 2 skilling.

And in the Characters screen the character's name could use something more to make it stand out.  Larger font to start with?  Some way of knowing which character you are viewing if you have scrolled past the name display.  Non-scrolling name headers?

**Comment by Morta1** [comment]
Hey @Zekaonar, I've added the additional information to the skill pages as suggested.

About selected preset, I don't think this data is saved on the cloud.

This has be added in [34ada4c](https://github.com/Morta1/IdleonToolbox/commit/34ada4c91d5933e558693ff16dcc0c6b8f707d48)
