### ISSUE TITLE
Storage Chests Missing

### ISSUE THREAD

**Issue by FierstArter** [Morta1/IdleonToolbox#113]
I believe that under Account > General there was a box that showed the storage chests upgrades you've gathered. It seems to be missing now.

Browser: Firefox

![image](https://user-images.githubusercontent.com/3493152/189920458-3c39d721-eacc-47bf-b100-53424ec12ffc.png)

**Comment by Morta1** [comment]
Hey, I don't this this ever existed, this is just a weird placeholder I've put there
