### ISSUE TITLE
Cogstruction export bug

### ISSUE THREAD

**Issue by Bolero-fk** [Morta1/IdleonToolbox#118]
I found the bug in the csv output by the Cogstruction feature.
Omni (Corner) Cog is output as a normal Cog.

I think your following code needs to be changed.

https://github.com/Morta1/IdleonToolbox/blob/1792f1a7eb1735720715a992617d2107505b4ef1/parsers/cogstrution.js#L46

Perhaps the following changes would fix the bug.
```js
 else if (name.includes('CogZ')) return 'Omni_Cog'; 
```

**Comment by Morta1** [comment]
@Bolero-fk Thanks for the report, do you mind checking it again?

**Comment by Morta1** [comment]
@Bolero-fk I've never really used cogstruction so I can't really test it myself 😅 
Committed with your suggested again

**Comment by Bolero-fk** [comment]
@Morta1 
Thanks Morta1!
I have confirmed that the bug has been fixed 🙆‍♂️

**Comment by Morta1** [comment]
Awesome !
Thanks for your help
