### ISSUE TITLE
Elemental Sorcerer Build

### ISSUE THREAD

**Issue by DrakeDragon5140** [Morta1/IdleonToolbox#119]
(Level 172)
Max Out: Mana Booster, Sharpened Axe, Gilded Sword, Book of the Wise, Overclocked Energy, Idle Casting
Extra Points in Quickness Boots 
Mage Tab
Max Out: Energy Bolt, Mini Fireball, Knowledge is Power, Unt'wis'tid Robes, Power Overwhelming, Individual Insight
Extra Points in: Mana Overdrive, You're Next
WIzard Tab
Max Out: Ice Shards, Floor is Lava, Tornado, Paperwork, Great..., Wis Wumbo, Fuscia Flasks
Extra points in Occult Obols
Elemental Sorcerer Tab
Max out: Utmost Intellect, The Family Guy, Memorial Skulls
Extra Points in: Meteor Shower, Dimensional Wormhole

**Comment by Morta1** [comment]
Please use the new feature to create custom builds in the [builds ](https://idleontoolbox.com/tools/builds)page
