### ISSUE TITLE
Item planner: Substract already owned components

### ISSUE THREAD

**Issue by dryslope** [Morta1/IdleonToolbox#125]
Hello,

When addind items to the item planner, the components of already crafted items should be removed from the requirements.

In this example, the required condensed zap should be only 1m, as we'll only need to craft 3 troll pants.

Same for the nullo salts, pearls, etc..

PS: Thanks for that great work, this website is extremely useful !

![image](https://github.com/Morta1/IdleonToolbox/assets/40764853/6d1244e3-e41c-4da5-b6bb-eab17614a005)

**Comment by Morta1** [comment]
Hey @dryslope, thanks for reporting,
Can you please send your idleontoolbox data from the home page here?

**Comment by dryslope** [comment]
My mistake, I didn't understand how to combine the checkboxes in the "display" section.
Checking the "missing items" did what I was looking for.

Tell me if you still want my data, otherwise you can close this.
