### ISSUE TITLE
Cogs grid : players with space in their name are partially displayed

### ISSUE THREAD

**Issue by m4as** [Morta1/IdleonToolbox#128]
Very low-impact bug in Account > World 3 > [Construction](https://github.com/Morta1/IdleonToolbox/blob/main/pages/account/world-3/construction.js#LL91C119-L91C119)

As a hobbyist developper without very good JS knowledge, I fixed it as below

```diff
-                <Tooltip title={<CogTooltip {...slot} character={cog?.name?.includes("Player") ? cog?.name?.split("_")[1] : ""} />}>
+                <Tooltip title={<CogTooltip {...slot} character={cog?.name?.includes("Player") ? cog?.name?.split("_")?.filter(function(i) { return i !== 'Player'; })?.join(' ') : ""} />}>
```

Same causes producing same effects, it is in Parsers > [Cogstruction](https://github.com/Morta1/IdleonToolbox/blob/main/parsers/cogstrution.js#LL10C83-L10C83) too :

```diff
-    const characterName = cogs[index].includes('Player_') ? cogs[index].split('_')[1] : '';
+    const characterName = cogs[index].includes('Player_') ? cogs[index].split('_').filter(function(i) { return i !== 'Player'; }).join(' ') : '';
```

**Comment by m4as** [comment]
Character names with spaces, in other words, with the .split[1] you only display first part of a character name if it is composed by two or more words  (Maas I, Maas II, Maas Luck etc.)
![image](https://github.com/Morta1/IdleonToolbox/assets/1342323/183c7643-20e2-4cb9-ade7-d23606430d83)

**Comment by Morta1** [comment]
Will be fixed
