### ISSUE TITLE
Dahsboard : usable tagged talents which have zero points are displayed as available/usable

### ISSUE THREAD

**Issue by m4as** [Morta1/IdleonToolbox#129]
Very low-impact bug in utility > dashboard > [characters.js](https://github.com/Morta1/IdleonToolbox/blob/main/utility/dashboard/characters.js#LL89C20-L89C20)

Dahsboard : a character with zero points in a talent he can have and which is tagged as a relevant one has it displayed as available.

As a hobbyist developper without very good JS knowledge, I fixed it as below

```diff
-    if (!talent || !configTalents?.[talent?.name]) return res;
+    if (!talent || talent?.level == 0 || !configTalents?.[talent?.name]) return res;
```

**Comment by Morta1** [comment]
Level 0 talents are needed for dashboard alert (incase the talent is leveled on another preset)
