### ISSUE TITLE
[Feature] Adding a note tab to make a TODO list

### ISSUE THREAD

**Issue by Anthony-Wratpor** [Morta1/IdleonToolbox#142]
Not an issue but it could be really usefull to add a todolist in the app to keep  track of progress of various things, i know we already have an item planner but i have some examples of things to remember that could be added to a list : 

- Quest i'm doing with each char
- What bubbles to focus at the moment
- Items/rare items i need to focus for recipes

might be other things that i don't think about right now

**Comment by Morta1** [comment]
Do you mean just a textual list with checkboxes?
Write your comment in https://discord.com/channels/1090610727334719558/1090611592611237960 :)

**Comment by Anthony-Wratpor** [comment]
Yes exactly, i know i can find it on any other websites, but i thougth it could be helpfull directly in the toolbox :)
It looks like the discord link is broken 
![image](https://github.com/Morta1/IdleonToolbox/assets/112498707/2c6814af-8fb9-4495-b434-b9c0f6acf505)
