### ISSUE TITLE
Missing search field on Inventory

### ISSUE THREAD

**Issue by eXpire163** [Morta1/IdleonToolbox#147]
Adding a search field on the character inventory would be a great QoL improvement.

## Usecases

- Searching all Power Statues to get the next Onyx Upgrade. 
- Find the lost Questitem
- etc.

## Implementation thoughts
- Extend the item "stack" by a filter that is passed to the component
- Add a dynamic search field to the character/index.jsx that only shows up if Inventory view is active

Btw. keep up your awesome work!!!

**Comment by Morta1** [comment]
There's the [item browser](https://idleontoolbox.com/tools/item-browser) page to find items all over your account
![image](https://github.com/Morta1/IdleonToolbox/assets/18611518/5c0c4d24-bf31-47af-96c8-65c851618a76)
