### ISSUE TITLE
Incorrect values for summoning Green/Yellow/Blue/etc gen per win upgrades

### ISSUE THREAD

**Issue by nohbdy** [Morta1/IdleonToolbox#152]
The upgrades that add essence generation based on how many green/blue/etc battles won are calculating the total bonus percentage using the previous tier of battle (AKA Green is calculated based of number of White wins, Yellow uses Green, etc).

Just to provide an example, I have 7 wins for white, 9 wins for green.  This upgrade gives 89% essence gen per green circuit win, and shows 801% (89% * 9) in game, but 623% (89% * 7) in IT.

![image](https://github.com/Morta1/IdleonToolbox/assets/181182/153cbc29-5062-48f1-b7fc-913cf3d7c851)

**Comment by Morta1** [comment]
Thanks 👍
