### ISSUE TITLE
Equinox charge rate appears to be incorrect in some instances

### ISSUE THREAD

**Issue by nohbdy** [Morta1/IdleonToolbox#157]
Some people in the discord were talking about equinox charge rates and penguins and someone reported a very high charge rate, after looking into it it appears you're double dipping a bit on penguins if they've purchased all 5 of them.

https://github.com/Morta1/IdleonToolbox/blob/a253c162f99c729c5224fddbd1f3553a44ba98e2/parsers/equinox.js#L39

If I'm understanding this correctly, it's giving a 1.5x multiplier if you've bought all the penguins in addition to the 10% multi per penguin (the accountOptions[320] bit)?

**Comment by Morta1** [comment]
Pushed a fix for it 🙏
