### ISSUE TITLE
Use NextJS router to change pages

### ISSUE THREAD

**Issue by Mohron** [Morta1/IdleonToolbox#2]
Currently, the Nav links that change pages cause the entire page to refresh which I thought was odd since I knew you were using Next.js. 

> Instead of setting the browser location like this:
https://github.com/Morta1/IdleonToolbox/blob/16ef0b3d2bfc502afda1600485f689541ecb706b/components/NavBar.js#L15

> Use Next.js's router like this:
https://nextjs.org/docs/api-reference/next/router#routerpush

And you'll get a clean client-side transition!

I look forward to seeing this project grow as it is super user-friendly and clean (idleon.site hurts my eyes haha).

**Comment by Morta1** [comment]
Been adding more and more features lately which leads to forgetting the little things. 
Thanks for the comment!
