### ISSUE TITLE
Frost Flake image named incorrectly

### ISSUE THREAD

**Issue by Mohron** [Morta1/IdleonToolbox#6]
![image](https://user-images.githubusercontent.com/3623122/133360971-bfd7b3f6-ec1b-4cbf-9c46-207f941a4289.png)
```html
<img title="Frost Flake" width="64" height="64" src="/IdleonToolbox/afk_targets/Frost_Flake.png" alt="">
```

https://github.com/Morta1/IdleonToolbox/blob/main/public/afk_targets/Frost_Flake_Idle.png

**Comment by Morta1** [comment]
Thanks, will be fixed in the next update.
