### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by FenixR** [Morta1/IdleonToolbox#89]
Hey, nice tool here are some suggestions that might be nice to have in it:

- ~~How many Cycles per hour happens on the refinery (Taking into account any bonus that reduces it like the laboratory one)~~
- 3D printer mats per hour vs Cycles per Hour for materials, to know how much you need to update your 3d Printers to achieve 100% uptime (besides Salts)
- ~~Hide some Stats per character, like I only want to watch all the worship values when picking all my characters.~~

Edit: I saw those those two where in there, pretty sure I missed it haha.

**Comment by Morta1** [comment]
I've actually added them after seeing your request lol
Thanks for the suggestion

**Comment by FenixR** [comment]
Glad to hear they might be useful haha. Here's another one if its possible:

- Item Planner for Quest: Pick a bunch of quest and get the items required to complete them all (Maybe with the additional requirements like monster kills and such).

- Skill Planner: Dunno if the formulas are available or if possible, to play around with the skills and see how it affects stuff like Damage and AFK gains.

**Comment by FenixR** [comment]
Oh yeah Cranium Cooking isn't tracked in the active skills either.

**Comment by FenixR** [comment]
last one for a while, its not possible to keep track of crystal countdown right? like what skill got boosted and by how much? Also, for the active exp calculator, would be nice to set the starting experience to not wait for the next update.

**Comment by Morta1** [comment]
I've added few of these features already, thanks for the suggestions
