### ISSUE TITLE
Dungeon timers count up instead of down

### ISSUE THREAD

**Issue by FloFri** [Morta1/IdleonToolbox#91]
Just a little thing: the timers in the dungeon page count up instead of down. 

The localType="countdown" attribute is missing in the Timer-tags in dungeon.js

Also in the file index.js of the timer component in line 24 it should be "setLocalType('countdown');" instead of "cooldown" according to line 69 in the same file.

**Comment by Morta1** [comment]
Thanks for the report, fixed in #93
