### ISSUE TITLE
Cogstruction export no longer works

### ISSUE THREAD

**Issue by FloFri** [Morta1/IdleonToolbox#92]
The cogstruction export no longer works. It only returns "undefined".

I think the problem is, in line 64 of "pages/account/world-3/construction.js" it should be "handleCopy(state?.account?.construction?.cogstruction?.cogData)" (the .account?-part is missing).

Also in line 67 I think it should be "handleCopy(state?.account?.construction?.cogstruction?.empties)" (.account? is missing and should be .empties at the end).

**Comment by Morta1** [comment]
Thanks for the report, fixed in #93
